### ISSUE TITLE
Exception during the SSL hand shake.

### ISSUE THREAD

**Issue by momalave** [sushilks/alexaHarmonyApp#7] opened 2016-03-02 10:05 UTC
I am getting an exception during the SSL hand shake. This is the error I get in my amazon echo cards: "The SSL handshake to endpoint Resource [https://xx.yyy.xxx.yy], Type [HTTP] failed. Please check that your java keystore is correctly configured" 

I followed the instructions to generate the Self-Signed Certificates. What did you put for: [subject_alternate_names]
DNS.1: ?????

I am not sure how to fix this problem. Please help.

**Comment by sushilks** [comment] 2016-03-02 11:07
Not sure what the problem is, you will need to provide more info. 
From what I remember it was not simple to get this part working. 
I am also not sure if using IP address instead of FQDN is allowed.

**Comment by momalave** [comment] 2016-03-02 11:38
This is my configuration.cnf file:
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
C = US
ST = CA
L = Palo Alto
O = Tiki Room
CN = Harmony Controller

[v3_req]
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @subject_alternate_names

[subject_alternate_names]
DNS.1 = 192.168.1.63

What should my FQDN be if you can not use an IP address?

What did you do to get this part to work? Are there any other steps that need to be done besides what is here https://developer.amazon.com/appsandservices/solutions/alexa/alexa-skills-kit/docs/testing-an-alexa-skill#create-a-private-key-and-self-signed-certificate-for-testing. Seems to be a trivial, but SSL Certificates are not being accepted for some reason. Please help (thanks for the quick reply).

**Comment by sushilks** [comment] 2016-03-02 18:56
The "DNS.1" entry is an IP address, others have also mentioned trouble
getting it to work with IP address. In my case I used a FQDN some thing
like "media.mywebserver.com".

**Comment by momalave** [comment] 2016-03-03 00:37
Hi sushilks,

Still no luck getting Amazon to do the proper handshake with my local server (I have confirmed that the request is being made via my router logs). Any tips or tricks (or checklist) for getting this to work? I would be really appreciate it. I really hope I can get your code working soon.

Here are the current errors:

When testing with amazon echo device here are the errors in the cards:
SSL handshake failed
Harmony Control

Request Identifier: amzn1.echo-api.request.[identifier #]

The SSL handshake to endpoint Resource [https://[my IP]], Type [HTTP] failed. Please check that your java keystore is correctly configured

When testing the skill in the browsers at developer.amazon.com. the error is:
There was an exception during the SSL hand shake. Please check the certificate you have provided.

Thanks again,
momalave

**Comment by momalave** [comment] 2016-03-03 01:25
Update: I was able to fix the SSL problem by created a free FQDN, but now I am getting this error:
There was an error calling the remote endpoint, which returned HTTP 404 : Not Found

I guess this is progress, but any ideas why this is happening?

Thanks,
momalave

**Comment by sushilks** [comment] 2016-03-03 04:51
That's good, I think this points to needing FQDN. 
I would debug the next problem by putting a tcpdump on the server port and checking if any connection is initiated from amazon cloud.
You also have to server on port 443 on the server, I am not sure if serving on other ports will work.

**Comment by joezorry** [comment] 2016-03-03 10:11
Sry, for my intrusion. 
But according to my experience the Echo communication must happen on port 443. 
However would love to be proven wrong.
Good find on the FQDN.

**Comment by momalave** [comment] 2016-03-03 13:57
Update: Problem solved. Here is how I fixed the issues
1) Create a FQDN using a free dynamic DNS hosting site (i.e. https://my.noip.com/ or https://duckdns.org) to avoid and SSL hand shake issue.
2) Finally, the last error was when I defined my endpoint for the alexa skill which needs to be https://[your FQDN]/remote, do not forget the /remote part or you will get the HTTP 404 error.

After these two problems were fixed, we are now in business. This is a great feature that the amazon echo is missing. Now I can eat dinner without getting grease on my remotes when wanting to pause or increase my tv volume lol. First world problems :-). If anybody has an issue, feel free to DM me, getting this to work took some time, but it should not be this hard. If you follow a few steps, it will work perfectly.
Take care and thanks for the support in getting this working.
-momalave

**Comment by joezorry** [comment] 2016-03-03 14:10
@momalave are you using the self-signed certificate that amazon has instructions for on their website?

**Comment by momalave** [comment] 2016-03-03 14:19
Yep, and it is working now.

**Comment by joezorry** [comment] 2016-03-03 19:28
@momalave I was also having some issues with SSL and this app, but guessing something wrong with my setup :smiley: 
Thx @momalave 

Gr8 work @sushilks on the app

So close on this issue?

**Comment by sushilks** [comment] 2016-03-03 19:36
Great, Thanks for posting the results @momalave. I will close the Issue.

**Closed as completed by sushilks** 2016-03-03 19:36 UTC

**Comment by momalave** [comment] 2016-03-05 11:26
Thanks for the help guys and great work on the app @sushilks.

**Comment by jokorea** [comment] 2017-05-05 04:08
hi. momalave.

I also have the same problem.
Could you provide more detail about your solution #1?

what is the final configuration.cnf file?
XXXXXXXXX
[subject_alternate_names]
DNS.1 = ????

I am not good English understanding for below:
Create a FQDN using a free dynamic DNS hosting site (i.e. https://my.noip.com/ or https://duckdns.org) to avoid and SSL hand shake issue.

Could you explain more detail again?
I created joalexa.hopto.org host name from https://my.noip.com/
Then what next my action steps?

I hope your good advice for my problem.

I am using AWS EC2 instance.
Here is my public DNS information.
Public DNS (IPv4)
ec2-34-196-111-188.compute-1.amazonaws.com
In this case, what should be my DNS.1 ?

Thanks
Seung-Man Jo

**Comment by kavuri** [comment] 2020-03-27 11:41
For anyone reaching this thread, your configuration can have the dynamically generated public AWS EC2 instance DNS, like:

```
[req]
distinguished_name = req_distinguished_name
x509_extensions = v3_req
prompt = no

[req_distinguished_name]
C = <>
ST = <>
L = <>
O = <>
CN = <>

[v3_req]
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @subject_alternate_names

[subject_alternate_names]
DNS.1 = ec2-12-213-160-230.ap-south-1.compute.amazonaws.com
```
